/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.ProdutoController;
import java.util.ArrayList;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produto;
import model.ProdutoDAO;

/**
 *
 * @author Aluno
 */
public class ProdutoGUI extends javax.swing.JFrame {

    private ProdutoController produtoController;

    /**
     * Creates new form ProdutoGUI
     */
    public ProdutoGUI(ProdutoController produtoController) {
        initComponents();
        this.produtoController = produtoController;
        popularTabela(produtoController.getAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        bntPorId = new javax.swing.JButton();
        bntResete = new javax.swing.JButton();
        bntCadastrar = new javax.swing.JButton();
        bntAlterar = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();
        bntPegarMaior = new javax.swing.JButton();
        bntPegarMenor = new javax.swing.JButton();
        bntPegarEntre = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblId.setLabelFor(txtId);
        lblId.setText("ID: ");

        lblNome.setLabelFor(txtNome);
        lblNome.setText("Nome:");

        lblValor.setLabelFor(txtValor);
        lblValor.setText("Preço:");

        bntPorId.setBackground(new java.awt.Color(0, 51, 102));
        bntPorId.setForeground(new java.awt.Color(255, 255, 255));
        bntPorId.setText("Buscar");
        bntPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPorIdActionPerformed(evt);
            }
        });

        bntResete.setBackground(new java.awt.Color(0, 51, 102));
        bntResete.setForeground(new java.awt.Color(255, 255, 255));
        bntResete.setText("Resete");
        bntResete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntReseteActionPerformed(evt);
            }
        });

        bntCadastrar.setBackground(new java.awt.Color(0, 51, 102));
        bntCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        bntCadastrar.setText("Cadastrar");
        bntCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadastrarActionPerformed(evt);
            }
        });

        bntAlterar.setBackground(new java.awt.Color(0, 51, 102));
        bntAlterar.setForeground(new java.awt.Color(255, 255, 255));
        bntAlterar.setText("Alterar");
        bntAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAlterarActionPerformed(evt);
            }
        });

        bntExcluir.setBackground(new java.awt.Color(0, 51, 102));
        bntExcluir.setForeground(new java.awt.Color(255, 255, 255));
        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        bntPegarMaior.setBackground(new java.awt.Color(0, 51, 102));
        bntPegarMaior.setForeground(new java.awt.Color(255, 255, 255));
        bntPegarMaior.setText("Pegar Maior");
        bntPegarMaior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPegarMaiorActionPerformed(evt);
            }
        });

        bntPegarMenor.setBackground(new java.awt.Color(0, 51, 102));
        bntPegarMenor.setForeground(new java.awt.Color(255, 255, 255));
        bntPegarMenor.setText("Pegar Menor");
        bntPegarMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPegarMenorActionPerformed(evt);
            }
        });

        bntPegarEntre.setBackground(new java.awt.Color(0, 51, 102));
        bntPegarEntre.setForeground(new java.awt.Color(255, 255, 255));
        bntPegarEntre.setText("Pegar Entre");
        bntPegarEntre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPegarEntreActionPerformed(evt);
            }
        });

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bntResete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bntCadastrar))
                            .addComponent(lblId)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bntPorId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bntPegarMaior)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bntPegarMenor))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(bntAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bntExcluir))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblValor)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(bntPegarEntre, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntPorId)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(bntPegarMaior)
                    .addComponent(bntPegarMenor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntPegarEntre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntAlterar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bntResete)
                        .addComponent(bntCadastrar)
                        .addComponent(bntExcluir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntReseteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntReseteActionPerformed
        txtId.setText("");
        txtNome.setText("");
        txtValor.setText("");
        txtId.requestFocus();
    }//GEN-LAST:event_bntReseteActionPerformed

    private void bntCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadastrarActionPerformed
        String nome = txtNome.getText();
        double valor = Double.valueOf(txtValor.getText());

        produtoController.cadastrar(nome, valor);
        JOptionPane.showMessageDialog(this, "Produto Cadastrado");
        popularTabela(produtoController.getAll());
    }//GEN-LAST:event_bntCadastrarActionPerformed

    private void bntPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPorIdActionPerformed
        int id = Integer.valueOf(txtId.getText());
        Optional<Produto> p = produtoController.getById(id);

        p.ifPresentOrElse(ps -> {
            txtNome.setText(ps.getNome());
            String valor = String.valueOf(ps.getValor());
            txtValor.setText(valor);
        }, () -> {
            txtNome.setText("");
            txtValor.setText("");
            JOptionPane.showMessageDialog(this, "Produto não encontrado");
        });
    }//GEN-LAST:event_bntPorIdActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this, "Tem ceteza que deseja excluir este Produto?", "Confirmas Exclusao",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (resposta == JOptionPane.YES_OPTION) {
            int id = Integer.valueOf(txtId.getText());
            if (produtoController.delete(id)) {
                JOptionPane.showMessageDialog(this, "Produto Excluido Com Sucesso");
                popularTabela(produtoController.getAll());
            } else {
                JOptionPane.showMessageDialog(this, "Produto não encontrado");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma alteração feita");
        }
        
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void bntAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAlterarActionPerformed
        int id = Integer.valueOf(txtId.getText());
        String nome = txtNome.getText();
        double valor = Double.valueOf(txtValor.getText());
        
        if(produtoController.update(id, nome, valor)){
          JOptionPane.showMessageDialog(this, "Produto alterado com sucesso");
          popularTabela(produtoController.getAll());
        } else {
          JOptionPane.showMessageDialog(this, "Produto não encontrado");
        }
    }//GEN-LAST:event_bntAlterarActionPerformed

    private void bntPegarMaiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPegarMaiorActionPerformed
        double valor = Double.valueOf(txtValor.getText());
        ArrayList<Produto> produtos = produtoController.getByValor(valor, true);
        popularTabela(produtos);
        if(produtos.isEmpty()){
        JOptionPane.showMessageDialog(this, "Nenhum produto encontrado");
        }
    }//GEN-LAST:event_bntPegarMaiorActionPerformed

    private void bntPegarMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPegarMenorActionPerformed
        double valor = Double.valueOf(txtValor.getText());
        ArrayList<Produto> produtos = produtoController.getByValor(valor, false);
        popularTabela(produtos);
        if(produtos.isEmpty()){
        JOptionPane.showMessageDialog(this, "Nenhum produto encontrado");
        }
    }//GEN-LAST:event_bntPegarMenorActionPerformed

    private void bntPegarEntreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPegarEntreActionPerformed
        double valor1 = Double.valueOf(JOptionPane.showInputDialog("Informe o valor minimo:"));
        double valor2 = Double.valueOf(JOptionPane.showInputDialog("Informe o valor maximo:"));
        ArrayList<Produto> produtos = produtoController.getByValor(valor1, valor2);
        popularTabela(produtos);
        if(produtos.isEmpty()){
        JOptionPane.showMessageDialog(this, "Nenhum produto encontrado");
        }
        
    }//GEN-LAST:event_bntPegarEntreActionPerformed

    public void popularTabela(ArrayList<Produto> produtos) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID:");
        model.addColumn("Nome:");
        model.addColumn("Preço:");

        for (Produto p : produtos) {
            model.addRow(new Object[]{p.getId(), p.getNome(), "R$" + p.getValor()});
        }
        tblProdutos.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProdutoDAO produtoDAO = new ProdutoDAO();
                ProdutoController produtoController = new ProdutoController(produtoDAO);
                new ProdutoGUI(produtoController).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAlterar;
    private javax.swing.JButton bntCadastrar;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntPegarEntre;
    private javax.swing.JButton bntPegarMaior;
    private javax.swing.JButton bntPegarMenor;
    private javax.swing.JButton bntPorId;
    private javax.swing.JButton bntResete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
